version: '3'

services:
  postgres:
    image: postgres:11.6
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=todo
      - POSTGRES_USER=todo
      - POSTGRES_DB=todo

  back:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DB_HOST=postgres
      - DB_USER=todo
      - DB_NAME=todo
      - DB_PASS=todo
    build: ./
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
