# Generated by Django 3.1.3 on 2020-12-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='To-Do')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('due_to', models.DateTimeField(null=True, verbose_name='Due to')),
                ('is_completed', models.BooleanField(verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='categories.category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todos.todo')),
            ],
            options={
                'verbose_name': 'TO-DO',
                'verbose_name_plural': "TO-DO's",
            },
        ),
    ]
